### ISSUE TITLE
Simplify header/query_param matching with custom matcher

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#100]
The following syntaxes are supported:

```yaml
headers:
  X-Example-Header: test
```

```yaml
headers:
  # multiple occurrences
  X-Example-Header: [test, test2, test3]
```

```yaml
headers:
  X-Example-Header:
    # array is required even for a single matcher
    - matcher: ShouldMatch
      value: test.*
```

The following should be allowed as well:

```yaml
headers:
  X-Example-Header: 
    # no array
    matcher: ShouldMatch
    value: test.*
```
