### ISSUE TITLE
Add header on proxy requests

### ISSUE THREAD

**Issue by pplr** [Thiht/smocker#130]
I propose to add a 'headers' property on proxy section to define headers to be injected in the request before sending to proxy destination.

For example:
```
proxy:
    host: https://example.com
    headers:
        X-Forwared-Proto: http
```

If ok, I can work on a pull request.
