### ISSUE TITLE
Mocks should be synchronized

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#14]
With this mock for example:

```yaml
request:
  method: GET
  path: /foo
context:
  times: 3
response:
  status: 200
```

If a client runs 10 calls in parallel to /foo, there's a risk that the mock server replies more than 3 times
