### ISSUE TITLE
Ugly button

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#140]
![Capture d’écran 2020-06-30 à 12 12 31](https://user-images.githubusercontent.com/2796344/86114583-06986700-bacb-11ea-8176-e6a57139a6c7.png)

The Reset button text is not centered, the padding is too narrow on the right.

Setting the following makes it better:

```css
.ant-btn>.anticon+span,
.ant-btn>span+.anticon {
    margin-left: initial;
}
```

but it makes the Add mocks and Visualize buttons uglier :/
