### ISSUE TITLE
Allow to refer to files in mock definitions

### ISSUE THREAD

**Issue by x80486** [Thiht/smocker#161]
I'm working with ancient APIs these days. The responses are JSON or XML files around 3,000 (even more) lines length.

I would like to use Smocker at the new work place, but so far I haven't found a way to do something like this with Smocker:

```yaml
- request:
    method: GET
    path: /hello/world
  response:
    headers:
      Content-Type: application/json
    body: file:/path/to/hello_world_response.json
```

I'm aware this not even valid YAML, but the `file:/path/to/hello_world_response.json` is just an example of what I'm trying to do, which is only to refer to a file with the content of the body, instead of putting the gigantic response there. If that's impossible to do these days, it would be nice to have a declarative way to implement such things in the YAML configuration file — probably with a fixed location for these kind of files.

> Moreover, those are usually _templates_, because there is always something that needs to be changed before sending them back to the user-agents.
