### ISSUE TITLE
Mock generator generates invalid body matcher

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#178]
When creating a new mock from entry an entry with a JSON body on the UI, something like this is generated:

```yml
- request:
    path: ...
    method: ...
    body:
      a:
        b: 3
```

instead of:

```yml
- request:
    path: ...
    method: ...
    body:
      a.b: 3
```

We should generate something following objx format, or not generate anything at all for the body
