### ISSUE TITLE
Different Response based on different field value in request JSON Body

### ISSUE THREAD

**Issue by donmstewart** [Thiht/smocker#189]
Hi

I am trying to test smoker to mock an API and am probably misunderstanding something.

I have a mock yaml that tests a single url with two requests defined. The first I would like to simulate a 200 OK and the JSON response for that. The second I am trying to simulate a 400 and the JSON response for that.

The mock deploys fine but I always get the 400 and it's associated response and never the 200. It seems it is not possible to differentiate between the requests using 

```yaml
body:
    matcher: ShouldEqualJSON
```

i.e. both requests are identical except for the value of a `name` field in the body of the request JSON.

The code for the mock is: -

```yaml
- request:
  # string matcher
  method: POST

  # string matcher
  path: /create/user/external

  # multi map matcher
  headers:
    Content-Type: application/json

  body:
    # either string matcher
    matcher: ShouldEqualJSON
    value: >
      {
          "name": "@fbar",
          "options": {}
      }
  dynamic_response:
    status: 200
    engine: go_template_yaml # mandatory string, indicates that the dynamic response must use the Go template engine
    script: > # mandatory string
      headers:
        Content-Type: [application/json]
      body: >
        {
          "status": "OK",
          "message": "",
          "data_type": "create_user_external_response",
          "data": "",
          "data_str": "{\"name\":\"{{.Request.Body.name}}\",\"info\":{}}"
        }
      delay:
        min: "0"
        max: 10ms
- request:
  # string matcher
  method: POST

  # string matcher
  path: /create/user/external

  # multi map matcher
  headers:
    Content-Type: application/json

  body:
    matcher: ShouldEqualJSON
    value: >
      {
          "name": "@fbar2",
          "options": {}
      }
  dynamic_response:
    status: 400
    engine: go_template_yaml # mandatory string, indicates that the dynamic response must use the Go template engine
    script: > # mandatory string
      headers:
        Content-Type: [application/json]
      body: >
        {        
          "status": "ERROR",
          "message": "Error: 'Duplicate name {{.Request.Body.name}} (S/SMc:3043); error (E/Ec:38); error in Job process'",
          "data_type": "none",
          "data": "",
          "data_str": ""
        }
      delay:
        min: "0"
        max: 10ms
```

Is this supported, am I doing it wrong or is there an issue?

Many thanks
