### ISSUE TITLE
Allow setting mock priority 

### ISSUE THREAD

**Issue by FelipeEmerim** [Thiht/smocker#219]
Hi,

I would like to be able to set priority for our mocks. Here is an example use case: 
I have a route for email validation which takes an email and returns 200 if valid, 400 if invalid. I would like to define it in smocker so that every email, except those that contain the substring "invalid" return a 200 response. So I used this:

```yaml
- request:
    path:
      matcher: ShouldEqual
      value: /api/v1/validation
    headers:
      Content-Type: application/json
    method:
      matcher: ShouldEqual
      value: POST
    body:
      api-key:
        matcher: ShouldNotBeEmpty
      email:
        matcher: ShouldContainSubstring
        value: invalid
  response:
    body: |
      {
        "message": "Invalid email"
      }
    status: 400
    headers:
      Content-Type:
        - application/json
  context: {}
  state:
    id: mail-token-validation-send-invalid-email
    times_count: 0
    locked: false
    creation_date: 2021-09-27T12:47:25.490914394Z

- request:
    path:
      matcher: ShouldEqual
      value: /api/v1/validation
    method:
      matcher: ShouldEqual
      value: POST
    headers:
      Content-Type: application/json
    body:
      api-key:
        matcher: ShouldNotBeEmpty
      email:
        matcher: ShouldNotBeEmpty
  response:
    body: |
      {
        "message": "Email valid"
      }
    status: 201
    headers:
      Content-Type:
        - application/json
  context: {}
  state:
    id: mail-token-validation-send-success
    times_count: 0
    locked: false
    creation_date: 2021-09-27T12:47:25.490914394Z
```

It does not work because it always uses the success mock(or the first matched mock). For that to work, the "invalid" mock would need to have a higher priority than the "valid" mock. I would love to help with this but my knowledge in go is pretty bad. I can help with testing though.
