### ISSUE TITLE
Setting `Host` header for proxy isn't working

### ISSUE THREAD

**Issue by tino** [Thiht/smocker#235]
I'm trying to run (from a docker container) with these proxy settings:
```yaml
  proxy:
      host: http://host.docker.internal:8000/
      headers:
          Host:
            - myapp.localhost
          X-foo-bar:
            - myval
```

This results in my app properly seeing the `X-foo-bar` header, but the `Host` header is still set to `host.docker.internal` (and my app doesn't like that). 

I have no idea how to fix this?
