### ISSUE TITLE
Dynamic mock on Query params 

### ISSUE THREAD

**Issue by Osku** [Thiht/smocker#248]
Hello

Can you provide a working sample of dynamic mock built on top of Query Params ? 

I tried : 
``` YAML
- request:
    method: GET
    path: /oauth/authorize
  dynamic_response:
    engine: go_template
    script: >
        headers:
          Location: "{{.Request.QueryParams.redirect_uri}}&code=ABCDE?state={{.Request.QueryParams.state}}"
        status: 302
```
It works almost. 
I got a Location header set with `[redirect_url_value]&code=ABCDE?state=[state_value]`

How could I remove these "[" and "]" ? 

Thanks in advance.

It is certainly not an issue.

**Comment by Osku** [comment]
I progress with : 
``` YAML
- request:
    method: GET
    path: /oauth/authorize
  dynamic_response:
    engine: go_template
    script: >
        headers:
          Location: "{{first .Request.QueryParams.redirect_uri}}&code=ABCDE?state={first {.Request.QueryParams.state}}"
        status: 302
```
I should just encode the URL now :)
