### ISSUE TITLE
Request Body matcher is saved incorrectly in mocks.yml

### ISSUE THREAD

**Issue by graeme-verticalscope** [Thiht/smocker#253]
### Summary

Smocker appears to add an extra `|` character when saving a request-body matcher to the `mocks.yml` file.

### Smocker Version

0.18.2 (using latest version of docker `thiht/smocker:latest`)

### Steps to Reproduce

1. In the UI, add a new POST mock. Configure the request body with `Default` -> `ShouldContainSubstring` matcher
![Screen Shot 2022-06-06 at 4 20 27 PM](https://user-images.githubusercontent.com/59446239/172243587-9d746dcb-fe6f-4286-af3e-9c4bba51b2e9.png)

2. Open `mocks.yml`

**Expected:**
body matcher is defined with yaml keys
```
- request:
    body:
        matcher: ShouldContainSubstring
        value: test-substring
```
**Actual:**
body matcher has extra `|` character, which starts a multi-line string
```
- request:
    body: |
        matcher: ShouldContainSubstring
        value: test-substring
```
