### ISSUE TITLE
Mock with path param

### ISSUE THREAD

**Issue by aswzen** [Thiht/smocker#262]
How to create a mock with a path params

For example hello/world/{param}

`- request:
    method: GET
    path: '/hello/world/{param}'
  response:
    status: 200`

The the param sent to response
'Hello {param}"

Thanks
Git

**Comment by gwleclerc** [comment]
Hi, you can use a string matcher to do that. https://smocker.dev/technical-documentation/mock-definition.html#string-matchers

```yaml
- request:
    methode: GET
    path:
      matcher: ShouldMatch
      value: /hello/world/.*
   response:
     status: 200
```
