### ISSUE TITLE
Combined query/body param matcher

### ISSUE THREAD

**Issue by Powerrr** [Thiht/smocker#278]
Sometimes we don't care if a particular parameter is sent in the query string or in the `application/x-www-form-urlencoded` body, because the application that we mock can consume that parameter either way. For such a case it would be nice if there was a way to setup a mock using some combined condition, smth. like
```yaml
- request:
    method: POST
    path: /foobar
    query_or_body_params:
      qwe: asd
  response:
    body: ok
```
so that it would match both `POST /foobar?qwe=asd` and `POST -H 'Content-type: application/x-www-form-urlencoded' /foobar --data 'qwe=asd'`. Basically, it would look for the `qwe` param both in the query and in the body.

(Currently my workaround is adding 2 mocks: one matches the query, another matches the body.)

So is it possible to add a feature like this?
