### ISSUE TITLE
Q: What is session and how to use it?

### ISSUE THREAD

**Issue by adaamz** [Thiht/smocker#279]
Hey,
firstly thanks for this tool, looks kinda early but I like it.

My first question is regarding sessions - what are they good for?
I would like to somehow categorize mocks per service (api server), so I see requests history for each service and I see mocks for that service.

My next question/bug - Why do I see mocks from only one session if I defined 2 sessions?
I have defined 2 sessions (can be api1, api2), when I click on second session I see defined mocks, but when I click on first session I see no mocks and I evne cannot add any mocks there (button is missing).

I use pretty straight-forward docker-compose.yml:
```yml
  mock-api:
    image: thiht/smocker
    environment:
      SMOCKER_PERSISTENCE_DIRECTORY: /tmp/smocker
    user: "1000"
    ports:
      - "10090:8080"
      - "10091:8081"
    volumes:
      - ./tests/smocker_sessions:/tmp/smocker
```

![image](https://github.com/Thiht/smocker/assets/4347332/9dd34c16-139e-4541-a808-35df2efa68ff)
![image](https://github.com/Thiht/smocker/assets/4347332/e00524b2-c380-434f-af87-3414ac6d9248)
