### ISSUE TITLE
Create a mock from a request

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#87]
A nice to have workflow would be the following:

- On a request in the history, click on a "+" (title: "Create mock from request")
- The mock editor opens, prefilled with:

```yml
- request:
    method:        # The request method
    path:          # The request path
    query_params:  # The request query params
    headers:       # The request headers (the user can remove the unnecessary ones as needed, but maybe we can filter some of them)
    # no body
- response:
    status: 200
    headers:
      Content-Type: application/json
    body: >
```
