### ISSUE TITLE
Extended body matching

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#99]
Right now, the request body is a basic `StringMatcher`. This limits a lot how we can manipulate it.
At the minimum, it would be nice to be able to perform rich matching on a JSON body field.

For example, if we want to match a body containing a `foobar` key with the value "Hello, World", for instance:

```json
{
  "foobar": "Hello, World"
}
```

the best we can do right now is something like:

```yaml
request:
  body:
    matcher: ShouldMatch
    value: '"foobar":\s*"Hello, World!"'
```

A better way to do it would be to apply matchers on the individual body field, by parsing it as JSON, for example:

```yaml
request:
  body:
    foobar: Hello, World
```

This allows us to apply powerful matching strategies, such as:

```yaml
request:
  body:
    foobar:
      matcher: ShouldMatch
      value: Hello, (.+)
```

For nested fields, the syntax could use [stretch/objx](https://github.com/stretchr/objx) (`.` for nested keys, `[n]` for arrays). Examples:

```yaml
request:
  body:
    my_array[2]: foo
    parent_key.child_key: bar
```
